//BOARD: LOLIN(WEMOS) D1 R2 & mini

#define WIFI_SSID_1    "WIFI 1 NAME"
#define WIFI_PASS_1    "WIFI 1 PASSWORD"

#define WIFI_SSID_2    "WIFI 2 NAME"
#define WIFI_PASS_2    "WIFI 2 PASSWORD"

#define IO_USERNAME    "ADAFRUIT IO USERNAME"
#define IO_KEY         "ADAFRUIT IO KEY"
